### ISSUE TITLE
Deletes

### ISSUE THREAD

**Issue by alex-thc** [domodwyer/merkle-search-tree#4]
This is an awesome project! I only see upserts though. Are deletes possible in MST?

**Comment by domodwyer** [comment]
Hey @alex-thc!

A MST is a [CRDT](https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type) and so does not support the typical "remove" operation because removing an entry from the tree may cause it to be re-added in a subsequent merge with a peer. It's not a valid CRDT operation as it is not a monotonic state change!

A typical way to "delete" something in a CRDT structure is to use a [tombstone](https://en.wikipedia.org/wiki/Tombstone_(data_store)) to mark the entry as deleted, and this would be expressed using this crate's MST by `upsert()`-ing a tombstone marker - something like:


```rust
enum Entry<T> {
    Active<T>,
    Deleted,
}

mst.upsert("bananas", Entry::Deleted); // It's gone!
```

I hope this helps!

**Comment by domodwyer** [comment]
(I'm going to close this, but feel free to reply :+1:)

**Comment by alex-thc** [comment]
Thanks, is this an MST design consideration or is it specific to your
implementation?

**Comment by domodwyer** [comment]
It's a necessary constraint for CRDTs to function correctly, so it is inherent to the MST data structure itself.

There may be an MST implementation out there that does provide a `delete()` method, but it's either implying the caller has to maintain a monotonic state themselves in order to maintain correctness, or it must provide an internal tombstone functionality which I think is probably better left to the application / protocol layer.
